version: "3"

services:

  uwsgi:
    # ビルドするDockerfileのディレクトリ相対パス
    build: ./api
    # コンテナ名
    container_name: BookShelfUwsgi
    # 指定したパスをコンテナにマウントする。"ホストのパス:コンテナのパス"となる
    volumes:
      - ./api:/var/api/
    # 解放するポートを指定。"ホスト:コンテナ"のマッピング となる
    ports:
      - "3031:3031"
    # コンテナ内の環境変数を指定する
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    container_name: BookShelfNginx
    volumes:
      - ./client/:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4231:80"
    environment:
      TZ: "Asia/Tokyo"

  postgresql:
    image: postgres:10.5
    container_name: BookShelfPostgresql
    ports:
      - 5432:5432
    volumes:
      - ./DB/init/:/docker-entrypoint-initdb.d
      - ./DB/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root
    environment:
      TZ: "Asia/Tokyo"
  
  pgadmin4:
    image: dpage/pgadmin4:3.3
    container_name: BookShelfPgadmin4
    ports:
      - 80:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
          - postgresql
    hostname: pgadmin4
  